### PR TITLE
Created new folder google with daydream controller model

### PR DESCRIPTION
**Pull request by TechnoBuddhist**
Created new folder called google with Google Daydream controller model, texture, etc...

### CODE REVIEW

**Comment by machenmusik** [comment]
A-Frame itself is MIT license, right?  presumably CDN assets used as part of core need same licensing?

**Comment by TechnoBuddhist** [comment]
For my part I'm happy to change the license, my concern was that the original author used CC Attributions and I wanted to make sure the license I chose covered it! Hands up I don't know anything about the details of licensing and maybe could have chosen something else; even none! As long as the original author(who I asked permission from anyway and received it) is covered I'm happy with whatever you guys decide.

**Comment by dmarcos** [comment]
@TechnoBuddhist Can we just add a README.md in the directory with the author attribution and postpone the license decision?

**Comment by TechnoBuddhist** [comment]
LICENSE removed, README contains attribution.

**Pull request merged**
