### PR TITLE
Update glTF assets to version 2.0

### PR DESCRIPTION
**Pull request by donmccurdy**

### CODE REVIEW

**Comment by dmarcos** [comment]
This models are only used by the examples, don't they? We should merge them after 0.7.0 to not break the current deployed site.

**Comment by donmccurdy** [comment]
How do you get to these on the deployed site? Like, I only see the showcase examples there, and https://aframe.io/examples/primitives/models/index.html is a 404.

Right now the examples won't work on `master` branch of course, so we could also put these models in a `2.0` folder and delete the old files after 0.7.0.

**Comment by dmarcos** [comment]
yeah we can put them in a folder and merge so people can run the examples on `master` locally. We would have to also update the URLs on the A-Frame examples

**Comment by donmccurdy** [comment]
Are only the showcase examples available on the main site? I'd like to understand what backwards-compatibility we are intending to keep here, for future reference.

**Comment by dmarcos** [comment]
Good question. I would not call it backwards compatibility it's more like an interim backards support until 0.7.0 ships. We cannot break the currently deployed site that relies on glTF 1.0 models and at the same time the examples on master should be able to run locally. For 0.7.0 release we can consolidate all the models and drop the glTF 1.0 ones. Does it sound too complicated? Am I missing anything?

**Comment by donmccurdy** [comment]
I guess what I'm asking is, what is it that we're trying not to break? I can't find any examples on the deployed site that use these models. For example, this page doesn't exist:

https://aframe.io/examples/primitives/models/index.html

Are only the showcase examples published?

**Comment by dmarcos** [comment]
yeah, it's a bit confusing that on the site we only expose a subset of the examples. The complete index is here: https://aframe.io/aframe/examples/ Your particular example: https://aframe.io/aframe/examples/primitives/models/index.html

**Comment by donmccurdy** [comment]
Ok! Good to know, yeah i'll move these to a different folder then.

**Comment by donmccurdy** [comment]
Moved everything to a subfolder. Will need one more PR on aframevr/aframe to point to the new folder.

**Comment by dmarcos** [comment]
Nice! Can you open the PR on A-Frame too so we can merge both at the same time?

**Comment by donmccurdy** [comment]
I'll open that PR, but there's no need to merge them at the same time... A-Frame master is currently pointed to the KhronosGroup/glTF-Sample-Models repo.

**Comment by donmccurdy** [comment]
Actually, it would be better to merge this first so I can actually test the other PR... do PRs merged here go live at https://cdn.aframe.io/* automatically?

**Comment by dmarcos** [comment]
The PR merged here are deployed in `https://aframe.io/assets/` and  `https://cdn.aframe.io` automatically. Merging!

**Pull request merged**
