### PR TITLE
add OpenVR controller models for Oculus Touch

### PR DESCRIPTION
**Pull request by machenmusik**

### CODE REVIEW

**Comment by machenmusik** [comment]
those are the original OpenVR names, I did not want to change them for clarity

**Comment by machenmusik** [comment]
the PNG file seems to be a texture file that is referenced when you load the obj and mtl files, but not sure how/if it is really used.  if someone with more modeling expertise can take a look at the latest OpenVR files, that may be beneficial...

**Comment by dmarcos** [comment]
I think it's fine changing the file names. Have you tried those models with your oculus touch https://github.com/aframevr/aframe/pull/2132?

**Comment by machenmusik** [comment]
yes I did try the models.  they work as well as the original @tbalouet page although it's just the controller model, no dynamic buttons etc. (which was known to be broken in the original page anyway)

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
