### PR TITLE
fix asset uploader

### PR DESCRIPTION
**Pull request by cvan**
updated with key for paid Uploadcare account

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks!

**Comment by ngokevin** [comment]
This is unlimited?

**Comment by cvan** [comment]
Essentially. Even with A-Painter, we're using 0.5% of our monthly bandwidth and only 450 MB of 0.5 TB.

**Comment by ngokevin** [comment]
BTW, thanks for this! What if we start pointing the community to upload assets through this tool? I guess we just cross that road when it comes?

**Comment by cvan** [comment]
> BTW, thanks for this! What if we start pointing the community to upload assets through this tool? I guess we just cross that road when it comes?

Yeah, we can. I have a different WIP asset uploader that's decentralised (actually distributed) I made (which doesn't have the Uploadcare dependency), but I haven't deployed it yet. If there's some interest from the community in working on that, can release that in the coming months and evangelise folks to use that.

**Pull request merged**
