### PR TITLE
Oculus model has discrete buttons & textures

### PR DESCRIPTION
**Pull request by TechnoBuddhist**
Broke model into separate buttons/textures
Includes Blender source files
Has less hidden geometry that was inside the model reducing poly count and file size by 20-25%

### CODE REVIEW

**Comment by machenmusik** [comment]
@dmarcos should the changed files be uploaded with new names for backward compatibility?

**Comment by machenmusik** [comment]
whether you release a new version or not, there will be 0.4.0 code out there (e.g. built-in using npm) and if you modify or remove its referenced CDN assets, you will break things (reference our earlier discussions on preference to break loudly)

**Comment by TechnoBuddhist** [comment]
So this would also be a good point to rename these to fall in line with vive and daydream...

vr_controller_touch_left....
vr_controller_touch_right....

?

**Comment by ngokevin** [comment]
I don't think it's worth breaking versioning for an internal filename. If you add an updated model, I'd just suffix it with a version.

**Comment by dmarcos** [comment]
@ngokevin I just don't want to have a lot of files with similar names that people might get confused with (do we need a changelog for models). In this case, besides updating the model, we want to also rename the file to follow the convention: `_` vs `-`. I I would just rename and update this model and will be more careful next time before pushing stuff to the release channel.

**Comment by machenmusik** [comment]
the usual ways to handle this: prefix, or suffix, or different paths for different versions.

**Comment by machenmusik** [comment]
it is convenient that renaming is required anyway to follow conventions here; allows delaying choice of paradigm.  as soon as this is in, will take a look at `oculus-touch-controls` unless anyone else gets there first

**Comment by ngokevin** [comment]
I'd just add like a `-v2` suffix or something? I don't imagine people will look at the filename or often browse this repo.

**Comment by TechnoBuddhist** [comment]
So renaming is a go! 

As dmarcos points "follow the convention: `_` vs `-`" But the other controllers don't! When I made the daydream controller I used the `_` because that was used on both Oculus and Vive. On Oculus it's now `-`, so if we are renaming then 'ideally' they would also need renaming.
If we duplicate controllers and the new dups use `-` then going fwd `-` is used in new code versions and you deprecate `_`? This mean no breaking changes.
Adding `-v2` is an option but we don't want to rename models using versioning, when the above would do the job!?
Speaking of convention I haven't seen a CONTRIBUTING.md or CODING_STANDARDS.md, or am I looking in the wrong place?. Maybe it's time!

**Comment by dmarcos** [comment]
It's the other way around. We deprecate `–` and keep `_`

**Comment by TechnoBuddhist** [comment]
Doh! So then it's a question of name. leave as is or add `-v2`. My pref is to not use `-v2` at least so early on in project's life.

**Comment by ngokevin** [comment]
Do we need to have conventions of asset filenames? I don't think we need to manage that closely, this repo is just a dump of assets so we don't have to host them on `aframevr/aframe`. People won't really visit this repo nor be typing out the filenames. I'm okay with whatever as long as we're not breaking a published version of A-Frame over dashes vs underscore.

**Comment by dmarcos** [comment]
I would be specially careful with those assets that are used by the core. It's very nice when things are consistent and predictable. I'm using the touch model and now I want a vive. If the name is consistent it's nicer and less error prone. Much more important in the long term than breaking something in version 0.4.0 that it's been out for a couple of weeks

**Comment by TechnoBuddhist** [comment]
@ngokevin I was thinking more general than assets, I haven't started looking at core or creating components yet, but CONTRIB and STDs docs would be useful, generalised more than canon(unless there are things that are definitely canon! tabs v spaces ;-))

So change to `-`(undoing the recent change), no `-v2` and we are good to go?
Do you just add a post in slack to say there are breaking changes?

**Comment by ngokevin** [comment]
I don't see much benefit in breaking it for the filename:

- The filename isn't exposed: `<a-entity vive-controls>` vs. `<a-entity oculus-controls>`.
- At least for me, I don't change asset URLs and hope they work, I look them up and copy/paste.
 
The issue is too minor to consider retroactively breaking a released version of an open source project. If we want to rename it, we can (I don't care for the filename consistency, overthinking IMO). But keep the old one lying around. Not many people dig through this repo.

**Comment by dmarcos** [comment]
I insist it's nice to have consistency across the board in the long term. Even to maintain aframe core. files use `_` all over the place in our projects. Let's maintain that. It's not discusion `-` vs `_`. There's already a convention and I want to stick with it. Let's keep `_` everywhere

**Comment by ngokevin** [comment]
Regarding `_` vs `-`, I don't really mind too much in terms of assets. But where are we using underscores in our projects? All the filenames across all of our projects use dashes, looking at the root of this repo, all the folders are dashes, our project names use dashes. Did you mean the other way around?

Again, as long as we don't break a released version of A-Frame over a style issue, I'm okay with whatever we want the assets to be named (because no one will see it :P).

**Comment by dmarcos** [comment]
@ngokeving yes, you're right. see? the inconsistency is confusing even to me that I deal with this everyday :P Let's keep `-` (dashes) everywhere then

**Comment by machenmusik** [comment]
other than a very strong preference for not breaking actual releases until deprecated by lifecycle (here, that means keeping referenced assets intact and in place unless you give the CDN instructions to redirect), i have no opinion on dashes vs. underscores etc.

as previously pointed out, the asset URLs are not exposed externally, I'd almost rather inline them if you are going to break the CDN URLs anytime in future.

but go ahead and pick whichever names to commit :-)

**Comment by dmarcos** [comment]
All right. Let's move on here. Let's move all the file names to dashes `-` and keep the old ones around as well. Would that work?

**Comment by ngokevin** [comment]
Yeah, works!

**Comment by TechnoBuddhist** [comment]
Ok let's see if this is correct and I got it right :-)

**Comment by dmarcos** [comment]
Right! I'll merge this and if someone complains out there I'll revert :) I will test this out more carefully on Monday when I'm back with my vive

**Pull request merged**
